name: InfinixMob
main: com.infinity3113.infinixmob.InfinixMob
version: 1.0.0
api-version: '1.20'
author: infinity3113
description: Un framework independiente para crear Mobs y Skills personalizadas.

commands:
  infinixmob:
    description: Comando principal de InfinixMob.
    aliases: [im]
    usage: /<command> [help|spawn|item|skills]
  cast:
    description: Lanza una habilidad de tu clase.
    usage: /<command> <1-4>
  skills:
    description: Abre el menú de habilidades de tu clase.
    aliases: [hab]
  classadmin: # <-- NUEVO COMANDO
    description: Administra la experiencia y puntos de habilidad de los jugadores.
    usage: /classadmin <exp|skillpoints> <add|set> <jugador> <cantidad>
    permission: infinixmob.admin

permissions:
  infinixmob.admin: # <-- NUEVO PERMISO
    description: Permite usar los comandos de administración de InfinixMob.
    default: op