name: InfinixMob
main: com.infinity3113.infinixmob.InfinixMob
version: 1.0.0
api-version: '1.20'
author: infinity3113
description: Un framework independiente para crear Mobs y Skills personalizadas.

commands:
  infinixmob:
    description: Comando principal de InfinixMob.
    aliases: [im]
    usage: /<command> [help|spawn|item|skills]